P85105\_hw3\_jw3597
================

#### Problem 1

This problem uses the BRFSS data. The data is loaded from the p8105.datasets package.

First we will do some data cleaning:

-   format the data to use appropriate variable names;
-   focus on the “Overall Health” topic
-   include only responses from “Excellent” to “Poor”
-   organize responses as a factor taking levels from “Excellent” to “Poor”

``` r
library(p8105.datasets)
data("brfss_smart2010")

# I am formatting the data using appropriate variable names, including only using responses from "Excellent" to "Poor", and then organizing the responses as a factor:
brfss_smart2010 = janitor::clean_names(brfss_smart2010) %>%
  rename(state = locationabbr, county = locationdesc, health_issue = class, health_issue_topic = topic, health_question = question, health_response = response, lower_95CI = confidence_limit_low, upper_95CI = confidence_limit_high) %>% 
  filter(health_response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>%
           mutate(health_response = factor(health_response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor"))) %>%
  arrange(health_response)
```

Using this dataset, I will answer the following (commenting on the results of each):

-   In 2002, which states were observed at 7 locations?
-   Make a “spaghetti plot” that shows the number of observations in each state from 2002 to 2010.
-   Make a table showing, for the years 2002, 2006, and 2010, the mean and standard deviation of the proportion of “Excellent” responses across locations in NY State.
-   For each year and state, compute the average proportion in each response category (taking the average across locations in a state). Make a five-panel plot that shows, for each response category separately, the distribution of these state-level averages over time.

In 2002, the states observed at 7 locations are

#### Problem 2

This problem uses the Instacart data. The data is loaded from the p8105.datasets package (called instacart).

The goal is to do some exploration of this dataset. To that end, write a short description of the dataset, noting the size and structure of the data, describing some key variables, and giving illstrative examples of observations. Then, do or answer the following (commenting on the results of each):

-   How many aisles are there, and which aisles are the most items ordered from?
-   Make a plot that shows the number of items ordered in each aisle. Order aisles sensibly, and organize your plot so others can read it.
-   Make a table showing the most popular item aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”
-   Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7 table).

``` r
data("instacart")

# Identifying the number of aisles and aisles with the most ordered items
uni = distinct(instacart, aisle_id)
count(uni)
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   134

``` r
sort(table(instacart$aisle_id), decreasing = TRUE)
```

    ## 
    ##     83     24    123    120     21    115     84    107     91    112 
    ## 150609 150473  78493  55240  41699  36617  32644  31269  26240  23635 
    ##     31     37    116     86     78     38      3     96     77    121 
    ##  23228  22676  22453  19875  19592  18221  17449  16957  16279  16201 
    ##     16     67     69     98     32     92     17    108    106     54 
    ##  16052  15142  15109  14350  13460  13198  13088  12820  12813  12694 
    ##     81    117     53     88     59     45    131     19     36     61 
    ##  12679  12532  12356  12102  11774  11453  11298  10620  10575   9980 
    ##      4     93     72      9     52     94    104    129     26    128 
    ##   9917   9851   9743   9736   9729   9376   9279   8870   8392   8353 
    ##    100     79     66     23     50    130     63    114     49     35 
    ##   8251   7661   7007   6917   6741   6352   6134   5894   5608   5208 
    ##     51     14     43    110    105     64     42     89     75     13 
    ##   5188   5123   5054   4882   4758   4742   4727   4719   4636   4133 
    ##     99      2     74     57     30     34     95    122     48     20 
    ##   3996   3873   3870   3803   3548   3341   3241   3159   3144   3070 
    ##      1     85      5     41     29     25    127     47    111     27 
    ##   2936   2906   2905   2885   2864   2773   2137   1969   1959   1839 
    ##      6     71     12     60     40     65     58      7      8     22 
    ##   1795   1729   1628   1621   1612   1612   1532   1526   1501   1469 
    ##    125     11     28     70     56     97     62     39    101     90 
    ##   1463   1346   1243   1205   1109   1094   1088   1084   1067   1062 
    ##    126    124     46    119     15    133     87     80     73     18 
    ##   1048    967    962    922    909    897    891    858    746    725 
    ##     76     68     33     44    118    109     55    103    134     10 
    ##    719    634    628    548    539    534    532    504    461    448 
    ##    102     82    113    132 
    ##    328    306    294    287

"Instacart" is a dataset that shows the online grocery orders of its users, containing 1,384,617 rows and 15 columns. Some of the key variables are the product name, aisle name and number where the product is found/categorized in, whether the item(s) were reordered, and the order ID that indicates the specific order placed by a customer. \* There are 134 aisles and the aisles with the most ordered items is 83 (most), 24, 123, and 120.

#### Problem 3

This problem uses the NY NOAA data. The data is loaded from the p8105.datasets package.

The goal is to do some exploration of this dataset. To that end, write a short description of the dataset, noting the size and structure of the data, describing some key variables, and indicating the extent to which missing data is an issue. Then, do or answer the following (commenting on the results of each):

-   Do some data cleaning. Create separate variables for year, month, and day. Ensure observations for temperature, precipitation, and snowfall are given in reasonable units. For snowfall, what are the most commonly observed values? Why?
-   Make a two-panel plot showing the average temperature in January and in July in each station across years. Is there any observable / interpretable structure? Any outliers?
-   Make a two-panel plot showing (i) tmax vs tmin for the full dataset (note that a scatterplot may not be the best option); and (ii) make a plot showing the distribution of snowfall values greater than 0 and less than 100 separately by year.

``` r
data("ny_noaa")
```
